---  
# Subdirectory in lmt_local_file_storage_path where troubleshooting data will be stored
lmt_troubleshooting_data_folder: "troubleshooting_data"
# Subdirectory in lmt_local_file_storage_path where collected scan results packages will be stored
lmt_scan_result_packages_folder: "scan_result_packages"
# Subdirectory in lmt_local_file_storage_path where cached scanner installers will be stored
lmt_scanner_installers_folder: "scanner_installers"
# Installation path on IBM i (constant)
lmt_scanner_path_ibmi: "/cit"
# required_window_space_in_MBs
lmt_scanner_windows_scanner_minimum_disk_space: 100
# required_linux_space_in_MBs
lmt_scanner_linux_scanner_minimum_disk_space: 100
# required_solaris_space_in_MBs
lmt_scanner_solaris_scanner_minimum_disk_space: 100
# required_aix_space_in_MBs
lmt_scanner_aix_scanner_minimum_disk_space: 100
# required_ibmi_space_in_MBs
lmt_scanner_ibmi_scanner_minimum_disk_space: 120
# Playbooks version - should be in-line with LMT server version and upgraded during each release
lmt_playbooks_version: "9.2.32.0"
#Vault passowrd
ilmt_main_server: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31303338393863376238656437653664376361333163356662353831613364336338333061633666
          3964623736396362663766363664616632383638363030660a353436353437323161383562633939
          63613833306234353266613132393161386461333432623463623131386264313134613830306566
          6133313366313130660a343764633832653736616661363137396439386663636432643637326261
          3266